name: Tests
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  packages:
    name: Test ${{ matrix.workspace }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workspace:
          - "@letsrunit/playwright"
          - "@letsrunit/bdd"
          - "@letsrunit/executor"
          - "@letsrunit/gherker"
          - "@letsrunit/controller"
          - "@letsrunit/gherkin"
          - "@letsrunit/mailbox"
          - "@letsrunit/journal"
          - "@letsrunit/utils"
          - "@letsrunit/ai"
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: yarn build:packages

      - name: Run Tests
        run: yarn workspace ${{ matrix.workspace }} test

  compat:
    name: Test ${{ matrix.workspace }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workspace:
          - "@letsrunit/compat-react"
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: yarn build:packages

      - name: Install Playwright Browsers
        run: yarn workspace ${{ matrix.workspace }} playwright install --with-deps

      - name: Run Tests
        run: yarn workspace ${{ matrix.workspace }} test
